# Generated by Django 3.0.6 on 2020-07-05 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20200704_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
