# Generated by Django 3.0.6 on 2020-07-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='twitter_user',
            new_name='pinged_user',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='read',
            new_name='received',
        ),
    ]
