# Generated by Django 3.0.6 on 2020-07-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='display_name',
        ),
    ]
